version: 0.2
phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip deployment_package.zip processFitbitData.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - export AWS_DEFAULT_REGION=us-east-1
      - aws lambda update-function-code --function-name ProcessFitbitData --zip-file fileb://deployment_package.zip || {echo "Updating Lambda function failed; exit 1;"}
      - echo "DONE!!"
artifacts:
  files:
    - deployment_package.zip